// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLxaN2dGhuSQflD-aoKkCpCCMKa1pjfsg',
    appId: '1:825921509384:web:784be5bece55bee12919bd',
    messagingSenderId: '825921509384',
    projectId: 'smart-ambulance-6df31',
    authDomain: 'smart-ambulance-6df31.firebaseapp.com',
    storageBucket: 'smart-ambulance-6df31.firebasestorage.app',
    measurementId: 'G-564YPMY9GK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFjJ0LLKf-g6xG3cz9eDbYuhdRlfv-_h8',
    appId: '1:825921509384:android:5e22de1959ebf39b2919bd',
    messagingSenderId: '825921509384',
    projectId: 'smart-ambulance-6df31',
    storageBucket: 'smart-ambulance-6df31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARQkEID2i_PdC6lECYGLicDu5Ny59iI6g',
    appId: '1:825921509384:ios:5268c0dc5e81f1792919bd',
    messagingSenderId: '825921509384',
    projectId: 'smart-ambulance-6df31',
    storageBucket: 'smart-ambulance-6df31.firebasestorage.app',
    iosClientId: '825921509384-bnf98r8goo2f805h2gdbesmu579lb5na.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARQkEID2i_PdC6lECYGLicDu5Ny59iI6g',
    appId: '1:825921509384:ios:5268c0dc5e81f1792919bd',
    messagingSenderId: '825921509384',
    projectId: 'smart-ambulance-6df31',
    storageBucket: 'smart-ambulance-6df31.firebasestorage.app',
    iosClientId: '825921509384-bnf98r8goo2f805h2gdbesmu579lb5na.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLxaN2dGhuSQflD-aoKkCpCCMKa1pjfsg',
    appId: '1:825921509384:web:557589162092633b2919bd',
    messagingSenderId: '825921509384',
    projectId: 'smart-ambulance-6df31',
    authDomain: 'smart-ambulance-6df31.firebaseapp.com',
    storageBucket: 'smart-ambulance-6df31.firebasestorage.app',
    measurementId: 'G-4DCBCTLVD3',
  );

}